package com.github.worn.domain.model

val capsuleWardrobeSuggestions: List<GapRecommendation> = listOf(
    // TOPS
    GapRecommendation(
        itemName = "White crew-neck tee",
        category = "TOPS",
        pairingCount = 0,
        subcategory = Subcategory.T_SHIRT,
        colors = listOf("White"),
        seasons = Season.entries.toList(),
        fit = Fit.SLIM_FIT,
        material = Material.COTTON,
        mappedCategory = Category.TOP,
    ),
    GapRecommendation(
        itemName = "Grey heather henley",
        category = "TOPS",
        pairingCount = 0,
        subcategory = Subcategory.HENLEY,
        colors = listOf("Grey"),
        seasons = listOf(Season.FALL, Season.WINTER),
        fit = Fit.REGULAR,
        material = Material.KNIT,
        mappedCategory = Category.TOP,
    ),
    GapRecommendation(
        itemName = "Polo shirt",
        category = "TOPS",
        pairingCount = 0,
        subcategory = Subcategory.POLO,
        colors = listOf("Black", "White"),
        seasons = listOf(Season.SPRING, Season.SUMMER),
        fit = Fit.SLIM_FIT,
        material = Material.COTTON,
        mappedCategory = Category.TOP,
    ),
    GapRecommendation(
        itemName = "White dress shirt",
        category = "TOPS",
        pairingCount = 0,
        subcategory = Subcategory.DRESS_SHIRT,
        colors = listOf("White"),
        seasons = Season.entries.toList(),
        fit = Fit.SLIM_FIT,
        material = Material.COTTON,
        mappedCategory = Category.TOP,
    ),
    // LAYERING
    GapRecommendation(
        itemName = "Navy zip-up hoodie",
        category = "LAYERING",
        pairingCount = 0,
        subcategory = Subcategory.HOODIE,
        colors = listOf("Navy"),
        seasons = listOf(Season.FALL, Season.WINTER),
        fit = Fit.REGULAR,
        material = Material.COTTON,
        mappedCategory = Category.OUTERWEAR,
    ),
    GapRecommendation(
        itemName = "Lightweight denim jacket",
        category = "LAYERING",
        pairingCount = 0,
        subcategory = Subcategory.TRUCKER,
        colors = listOf("Light Blue"),
        seasons = listOf(Season.SPRING, Season.FALL),
        fit = Fit.REGULAR,
        material = Material.DENIM,
        mappedCategory = Category.OUTERWEAR,
    ),
    // BOTTOMS
    GapRecommendation(
        itemName = "Dark wash straight jeans",
        category = "BOTTOMS",
        pairingCount = 0,
        subcategory = Subcategory.JEANS,
        colors = listOf("Navy"),
        seasons = Season.entries.toList(),
        fit = Fit.REGULAR,
        material = Material.DENIM,
        mappedCategory = Category.BOTTOM,
    ),
    GapRecommendation(
        itemName = "Chino pants",
        category = "BOTTOMS",
        pairingCount = 0,
        subcategory = Subcategory.CHINOS,
        colors = listOf("Beige", "Khaki"),
        seasons = Season.entries.toList(),
        fit = Fit.REGULAR,
        material = Material.COTTON,
        mappedCategory = Category.BOTTOM,
    ),
    GapRecommendation(
        itemName = "Tailored pants",
        category = "BOTTOMS",
        pairingCount = 0,
        subcategory = Subcategory.TAILORED_PANTS,
        colors = listOf("Navy", "Charcoal"),
        seasons = Season.entries.toList(),
        fit = Fit.SLIM_FIT,
        material = Material.WOOL,
        mappedCategory = Category.BOTTOM,
    ),
    // SHOES
    GapRecommendation(
        itemName = "White leather sneakers",
        category = "SHOES",
        pairingCount = 0,
        subcategory = Subcategory.SNEAKERS,
        colors = listOf("White"),
        seasons = Season.entries.toList(),
        material = Material.LEATHER,
        mappedCategory = Category.SHOES,
    ),
    GapRecommendation(
        itemName = "Chelsea boots",
        category = "SHOES",
        pairingCount = 0,
        subcategory = Subcategory.BOOTS_CHELSEA,
        colors = listOf("Brown"),
        seasons = listOf(Season.FALL, Season.WINTER),
        material = Material.LEATHER,
        mappedCategory = Category.SHOES,
    ),
    GapRecommendation(
        itemName = "Derby dress shoes",
        category = "SHOES",
        pairingCount = 0,
        subcategory = Subcategory.DERBY,
        colors = listOf("Black"),
        seasons = Season.entries.toList(),
        material = Material.LEATHER,
        mappedCategory = Category.SHOES,
    ),
    // ACCESSORIES
    GapRecommendation(
        itemName = "Brown leather belt",
        category = "ACCESSORIES",
        pairingCount = 0,
        subcategory = Subcategory.BELT,
        colors = listOf("Brown"),
        seasons = Season.entries.toList(),
        material = Material.LEATHER,
        mappedCategory = Category.ACCESSORY,
    ),
)
